---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: base-debian-gpg
    image: debian:buster
  - name: base-ubuntu-gpg
    image: ubuntu:18.04
  - name: base-fedora-gpg
    image: fedora:31
  - name: base-centos-gpg
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
