---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-debian-gpg
    image: debian:buster
  - name: base-ubuntu-gpg
    image: ubuntu:18.04
  - name: base-fedora-gpg
    image: fedora:31
  - name: base-centos-gpg
    image: centos:7
provisioner:
  name: ansible
verifier:
  name: ansible
